[build]
  publish = "build/web"
  command = """
    set -e
    export FLUTTER_VERSION=${FLUTTER_VERSION:-3.24.5}
    
    # Verificar si la rama empieza con 'release', es 'main' o si es deploy-preview
    if [[ "$BRANCH" =~ ^release ]] || [[ "$BRANCH" == "main" ]] || [[ "$CONTEXT" == "deploy-preview" ]]; then
      echo "Building for branch: $BRANCH, context: $CONTEXT"
      
      # Descargar Flutter para Linux
      curl -L -o flutter.tar.xz \
        https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${FLUTTER_VERSION}-stable.tar.xz
      tar -xJf flutter.tar.xz
      export PATH="$PATH:`pwd`/flutter/bin"
      
      # Cache pub para acelerar builds
      export PUB_CACHE="/opt/buildhome/.pub-cache"
      mkdir -p $PUB_CACHE

      flutter --version
      flutter config --enable-web
      flutter pub get
      flutter build web --release
    else
      echo "Skipping build for branch: $BRANCH, context: $CONTEXT (not main, release branch or deploy-preview)"
      exit 0
    fi
  """

[build.environment]
  FLUTTER_VERSION = "3.24.5"
  PUB_CACHE = "/opt/buildhome/.pub-cache"

# Configuración para deploy-preview (PRs)
[context.deploy-preview]
  command = """
    set -e
    export FLUTTER_VERSION=${FLUTTER_VERSION:-3.24.5}
    
    echo "Building deploy-preview for branch: $BRANCH"
    
    # Descargar Flutter para Linux
    curl -L -o flutter.tar.xz \
      https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${FLUTTER_VERSION}-stable.tar.xz
    tar -xJf flutter.tar.xz
    export PATH="$PATH:`pwd`/flutter/bin"
    
    # Cache pub para acelerar builds
    export PUB_CACHE="/opt/buildhome/.pub-cache"
    mkdir -p $PUB_CACHE

    flutter --version
    flutter config --enable-web
    flutter pub get
    flutter build web --release
  """
  publish = "build/web"

# Configuración de redirecciones para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache para assets estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache para archivos JS y CSS
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"