// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcP5xB0-MVBaUsVZSQPh5VgjsY8SxjLyQ',
    appId: '1:756178976224:web:532c76c56b362dbdcabf85',
    messagingSenderId: '756178976224',
    projectId: 'devboard-6c37e',
    authDomain: 'devboard-6c37e.firebaseapp.com',
    storageBucket: 'devboard-6c37e.firebasestorage.app',
    measurementId: 'G-8MBXG7RLSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZUFCb8ifvbMW1eORrl9r7TenWOHQDqXw',
    appId: '1:756178976224:android:2144ed8b5c1faf34cabf85',
    messagingSenderId: '756178976224',
    projectId: 'devboard-6c37e',
    storageBucket: 'devboard-6c37e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR6TEvQ-CWDkiLaA_SPH4B1AkfzxC343Y',
    appId: '1:756178976224:ios:a67f1a55a144b81dcabf85',
    messagingSenderId: '756178976224',
    projectId: 'devboard-6c37e',
    storageBucket: 'devboard-6c37e.firebasestorage.app',
    iosBundleId: 'com.example.DevBoard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR6TEvQ-CWDkiLaA_SPH4B1AkfzxC343Y',
    appId: '1:756178976224:ios:a67f1a55a144b81dcabf85',
    messagingSenderId: '756178976224',
    projectId: 'devboard-6c37e',
    storageBucket: 'devboard-6c37e.firebasestorage.app',
    iosBundleId: 'com.example.DevBoard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcP5xB0-MVBaUsVZSQPh5VgjsY8SxjLyQ',
    appId: '1:756178976224:web:150d9a311a69fea9cabf85',
    messagingSenderId: '756178976224',
    projectId: 'devboard-6c37e',
    authDomain: 'devboard-6c37e.firebaseapp.com',
    storageBucket: 'devboard-6c37e.firebasestorage.app',
    measurementId: 'G-S0RRW9CY6F',
  );
}
